version: '3'
services:
  yomiage_voicevox:
    container_name: yomiage_voicevox
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./yomiage_VOICEVOX:/yomiage_VOICEVOX
    environment:
      TOKEN: "TOKEN"
      TZ: "Asia/Tokyo"
      COMMAND_SYNTHAX : "!"
      COMMENT_SYNTHAX : ">"
      OTHER_BOTS_SYNTHAX : "$$,%,*"
    entrypoint: "python3 /yomiage_VOICEVOX/python_code/discordbot.py"