version: '3'
services:
  yomiage_voicevox:
    container_name: yomiage_voicevox
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./yomiage_VOICEVOX:/yomiage_VOICEVOX
    environment:
      TZ: "Asia/Tokyo"
      TOKEN: "TOKEN"
      COMMAND_SYNTHAX : "!"
      COMMENT_SYNTHAX : ">"
      OTHER_BOTS_SYNTHAX : "$$,%,*"
      USE_VOICEVOX: True
      USE_COEIROINK: True
      USE_LMROID: False
      USE_SHAREVOX: False
      FLAG_LIST_PATH: "data/flag_list.csv"
      VOICE_LIST_PATH: "data/voice_list.csv"
      WORD_LIST_PATH: "data/word_list.csv"
      STYLE_SETTING_PATH: "data/style_setting.csv"
    entrypoint: "python3 /yomiage_VOICEVOX/discordbot.py"